import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class SolutionTest {
  @Test
  public void test() {
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, true, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, true, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, true, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, true, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, true, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, true, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {false, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true, true}));
    assertTrue(Logic.multImplication(new boolean[] {false, false}));
    assertTrue(Logic.multImplication(new boolean[] {false, true}));
    assertFalse(Logic.multImplication(new boolean[] {true, false}));
    assertTrue(Logic.multImplication(new boolean[] {true, true}));
    assertFalse(Logic.multImplication(new boolean[] {false}));
    assertTrue(Logic.multImplication(new boolean[] {true}));
    assertFalse(Logic.multImplication(new boolean[] {}));
  }
}
