version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    target-branch: develop
    milestone: 6
    labels:
      - "chore"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: develop
    milestone: 6
    labels:
      - "chore"