  version: 2
  updates:
    - package-ecosystem: gradle
      directory: /
      schedule:
        interval: daily
      target-branch: develop
      milestone: ${{secrets.VERSION}}
      labels:
        - "chore"