version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    milestone: 13
    labels:
      - "chore"
    groups:
      spring:
        patterns:
          - "org.springframework.boot:spring-boot-starter-web"
          - "org.springframework.boot:spring-boot-starter-test"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    milestone: 13
    labels:
      - "chore"