version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    milestone: 7
    labels:
      - "chore"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    milestone: 7
    labels:
      - "chore"