name: Clean-up cache after PR closed

on:
  pull_request:
    types: [ closed ]

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache Cleanup
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          BRANCH: "refs/pull/${{ github.event.pull_request.number }}/merge"
        run: |
          cacheKeysForPR=$(gh cache list --repo $REPO --ref $BRANCH | cut -f 1)
          for cacheKey in $cacheKeysForPR
          do
            gh cache delete $cacheKey --repo $REPO
          done
