name: Clear dependency graph for a correlator

on:
  workflow_dispatch:
    inputs:
      job-correlator:
        description: Key that is used to group snapshots submitted over time

jobs:
  clean-up:
    runs-on: ubuntu-22.04
    steps:
      - name: Set current timestamp as env variable
        run: echo "NOW=$(date -Iseconds)" >> $GITHUB_ENV
      - name: Submit empty dependency graph
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots \
          -d '{ "version" : 0, "job" : { "id" : "${{ github.run_id }}", "correlator" : "${{ inputs.job-correlator }} " }, "sha" : "${{ github.sha }}", "ref" : "${{ github.ref }}",  "detector" : { "name" : "GitHub Dependency Graph Gradle Plugin", "version" : "0.0.3", "url" : "https://github.com/gradle/github-dependency-graph-gradle-plugin" }, "manifests" : {}, "scanned" : "${{ env.NOW }}" }'