name: Update Gradle Wrapper

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@981c551b17dbcf1940b1b4435afdb79babb7c13a
        with:
          base-branch: develop
          target-branch: develop
          labels: chore